"""Static and mechanical furniture pipeline."""

from __future__ import annotations

from math import radians

from . import common


def generate(spec: dict) -> dict:
    mats = common.prepare_scene(spec, frame_end=72)
    parts = []
    animated_root = None

    tabletop = common.cube("PROP_AgentFurniture_Tabletop", (0, 0, 0.78), (1.25, 0.72, 0.08), mats["primary"], bevel=0.045, collection_name="PROPS")
    parts.append(tabletop)
    for x in (-0.52, 0.52):
        for y in (-0.28, 0.28):
            parts.append(common.cylinder("PROP_AgentFurniture_TaperedLeg", (x, y, 0.39), 0.055, 0.7, mats["dark"], vertices=18, collection_name="PROPS"))
            parts.append(common.cylinder("PROP_AgentFurniture_FootCap", (x, y, 0.04), 0.072, 0.05, mats["secondary"], vertices=18, collection_name="PROPS"))
    parts.append(common.cube("PROP_AgentFurniture_BackRail", (0, 0.39, 1.06), (1.22, 0.05, 0.16), mats["secondary"], bevel=0.035, collection_name="PROPS"))
    parts.append(common.cube("PROP_AgentFurniture_LowerShelf", (0, 0, 0.42), (1.02, 0.58, 0.035), mats["dark"], bevel=0.025, collection_name="PROPS"))

    for index, label in enumerate((spec.get("requiredParts") or [])[:5]):
        x = -0.48 + index * 0.24
        marker = common.cube(f"PROP_AgentFurniture_Detail_{index + 1}", (x, -0.18, 0.89), (0.07, 0.08, 0.025), mats["accent"], bevel=0.012, collection_name="PROPS")
        marker["asset_part_hint"] = label
        parts.append(marker)

    parts.append(common.add_contact_shadow("PROP_AgentFurniture_ContactShadow", 0.92))

    if spec.get("animationClips"):
        animated_root = common.create_empty("ANIM_AgentFurniture_MechanicalRoot", "PROPS", (0, 0, 0.78))
        for obj in [tabletop]:
            common.parent_keep_world(obj, animated_root)
        clip_name = spec["animationClips"][0]["name"]
        common.create_action(
            animated_root,
            clip_name,
            [
                (1, {"rotation": (0, 0, 0)}),
                (36, {"rotation": (0, 0, radians(3.5))}),
                (72, {"rotation": (0, 0, 0)}),
            ],
            end=72,
        )
        parts.append(animated_root)

    common.setup_lighting_and_camera(spec, camera_loc=(2.15, -4.3, 1.5), target=(0, 0, 0.62))
    paths = common.export_asset(spec, parts, animations=bool(spec.get("animationClips")), frame=24)
    return common.collect_metadata(
        spec,
        paths,
        rig={
            "type": spec.get("rigTarget", "none"),
            "root": animated_root.name if animated_root else "",
            "animated_controls": [animated_root.name] if animated_root else [],
        },
        notes=[
            "Generated by the reusable OnTheSpectrum furniture pipeline.",
            "Furniture uses transform animation only when clips are requested.",
            "Mixamo exports are intentionally omitted for furniture assets.",
        ],
    )
