"""Botanical asset pipeline."""

from __future__ import annotations

from math import radians

from . import common


def generate(spec: dict) -> dict:
    mats = common.prepare_scene(spec, frame_end=84)
    parts = []
    plant = spec.get("plant") or {}
    leaf_shape = str(plant.get("leafShape", "rounded")).lower()
    blossom_style = str(plant.get("blossomStyle", "small accent blossoms")).lower()
    leaf_scale = (0.24, 0.026, 0.055) if "needle" in leaf_shape or "thin" in leaf_shape else (0.16, 0.06, 0.11) if "broad" in leaf_shape else (0.19, 0.035, 0.08)
    sway_root = common.create_empty("ANIM_AgentPlant_SwayRoot", "PROPS", (0, 0, 0.12))

    trunk = common.bevel_curve(
        "PROP_AgentPlant_CurvedStem",
        [(0, 0, 0.04), (0.04, 0, 0.65), (-0.06, 0.02, 1.25), (0, 0, 1.72)],
        mats["dark"],
        bevel_depth=0.055,
        collection_name="PROPS",
    )
    parts.extend([sway_root, trunk])
    common.parent_keep_world(trunk, sway_root)

    for index in range(9):
        z = 0.42 + index * 0.14
        side = -1 if index % 2 else 1
        leaf = common.uv_sphere(
            f"PROP_AgentPlant_Leaf_{index + 1}",
            (0.18 * side, 0.025 * index, z),
            leaf_scale,
            mats["primary"],
            segments=24,
            rings=10,
            collection_name="PROPS",
        )
        leaf.rotation_euler.z = radians(18 * side)
        common.parent_keep_world(leaf, sway_root)
        parts.append(leaf)

    blossom_scale = (0.36, 0.28, 0.12) if "flat" in blossom_style else (0.22, 0.22, 0.3) if "tall" in blossom_style or "spire" in blossom_style else (0.32, 0.32, 0.2)
    blossom = common.uv_sphere("PROP_AgentPlant_BlossomCluster", (0, 0, 1.83), blossom_scale, mats["secondary"], segments=32, rings=12, collection_name="PROPS")
    core = common.uv_sphere("PROP_AgentPlant_GlowPollen", (0, -0.04, 1.84), (0.11, 0.11, 0.075), mats["accent"], segments=20, rings=8, collection_name="PROPS")
    parts.extend([blossom, core])
    common.parent_keep_world(blossom, sway_root)
    common.parent_keep_world(core, sway_root)
    parts.append(common.add_contact_shadow("PROP_AgentPlant_ContactShadow", 0.45))

    if spec.get("animationClips"):
        clip_name = spec["animationClips"][0]["name"]
        common.create_action(
            sway_root,
            clip_name,
            [
                (1, {"rotation": (0, 0, 0)}),
                (21, {"rotation": (radians(2.2), radians(-1.2), radians(0.8))}),
                (42, {"rotation": (0, 0, 0)}),
                (63, {"rotation": (radians(-1.6), radians(1.4), radians(-0.8))}),
                (84, {"rotation": (0, 0, 0)}),
            ],
            end=84,
        )

    common.setup_lighting_and_camera(spec, camera_loc=(2.15, -5.2, 2.2), target=(0, 0, 1.05))
    paths = common.export_asset(spec, parts, animations=bool(spec.get("animationClips")), frame=21)
    return common.collect_metadata(
        spec,
        paths,
        rig={
            "type": spec.get("rigTarget", "simple transform rig"),
            "root": sway_root.name,
            "animated_controls": [sway_root.name] if spec.get("animationClips") else [],
            "family_preset": plant.get("botanicalType", spec.get("name", "plant")),
        },
        notes=[
            "Generated by the reusable OnTheSpectrum botanical pipeline.",
            "Plant motion is embedded as lightweight transform sway.",
            "Mixamo exports are intentionally omitted for plant assets.",
        ],
    )
