"""Static and display-motion prop pipeline."""

from __future__ import annotations

from math import radians

from . import common


def generate(spec: dict) -> dict:
    mats = common.prepare_scene(spec, frame_end=96)
    parts = []
    root = common.create_empty("PROP_AgentProp_Root", "PROPS", (0, 0, 0.72))
    prop = spec.get("prop") or {}
    category = prop.get("category", "custom")

    if category in {"tool", "weapon"}:
        body = common.cylinder("PROP_AgentProp_PrimaryForm", (0, 0, 0.78), 0.12, 0.86, mats["primary"], vertices=28, rotation=(0, radians(90), 0), collection_name="PROPS")
    elif category in {"container", "machine", "treasure"}:
        body = common.cube("PROP_AgentProp_PrimaryForm", (0, 0, 0.68), (0.46, 0.34, 0.38), mats["primary"], bevel=0.055, collection_name="PROPS")
    else:
        body = common.uv_sphere("PROP_AgentProp_PrimaryForm", (0, 0, 0.72), (0.42, 0.34, 0.52), mats["primary"], segments=32, rings=16, collection_name="PROPS")
    band = common.cylinder("PROP_AgentProp_EquatorBand", (0, 0, 0.72), 0.46, 0.055, mats["secondary"], vertices=48, rotation=(1.5708, 0, 0), collection_name="PROPS")
    cap = common.cylinder("PROP_AgentProp_BaseCap", (0, 0, 0.21), 0.32, 0.12, mats["dark"], vertices=40, collection_name="PROPS")
    parts.extend([root, body, band, cap])
    for obj in (body, band, cap):
        common.parent_keep_world(obj, root)

    for index, label in enumerate((spec.get("requiredParts") or [])[:8]):
        angle = index * 0.785
        x = 0.46 * __import__("math").cos(angle)
        y = 0.46 * __import__("math").sin(angle)
        detail = common.uv_sphere(f"PROP_AgentProp_Detail_{index + 1}", (x, y, 0.82), (0.055, 0.055, 0.055), mats["accent"], segments=16, rings=8, collection_name="PROPS")
        detail["asset_part_hint"] = label
        common.parent_keep_world(detail, root)
        parts.append(detail)
    if category == "beacon":
        beam = common.bevel_curve("PROP_AgentProp_BeaconBeam", [(0, 0, 0.94), (0, 0, 1.25), (0, 0, 1.52)], mats["accent"], bevel_depth=0.026, collection_name="PROPS")
        common.parent_keep_world(beam, root)
        parts.append(beam)
    if category in {"tool", "weapon"}:
        handle = common.cylinder("PROP_AgentProp_Grip", (-0.42, 0, 0.78), 0.085, 0.26, mats["dark"], vertices=24, rotation=(0, radians(90), 0), collection_name="PROPS")
        common.parent_keep_world(handle, root)
        parts.append(handle)
    if category in {"container", "treasure"}:
        lid = common.cube("PROP_AgentProp_Lid", (0, -0.01, 0.92), (0.5, 0.36, 0.07), mats["secondary"], bevel=0.035, collection_name="PROPS")
        common.parent_keep_world(lid, root)
        parts.append(lid)
    parts.append(common.add_contact_shadow("PROP_AgentProp_ContactShadow", 0.58))

    if spec.get("animationClips"):
        clip_name = spec["animationClips"][0]["name"]
        common.create_action(
            root,
            clip_name,
            [
                (1, {"rotation": (0, 0, 0)}),
                (48, {"rotation": (0, 0, radians(180))}),
                (96, {"rotation": (0, 0, radians(360))}),
            ],
            end=96,
        )

    common.setup_lighting_and_camera(spec, camera_loc=(1.9, -4.4, 1.6), target=(0, 0, 0.72))
    paths = common.export_asset(spec, parts, animations=bool(spec.get("animationClips")), frame=24)
    return common.collect_metadata(
        spec,
        paths,
        rig={
            "type": spec.get("rigTarget", "none"),
            "root": root.name,
            "animated_controls": [root.name] if spec.get("animationClips") else [],
            "family_preset": category,
        },
        notes=[
            "Generated by the reusable OnTheSpectrum prop pipeline.",
            "Optional display motion is embedded as GLB transform animation.",
            "Mixamo exports are intentionally omitted for prop assets.",
        ],
    )
