"""GLB-safe baked mesh and curve VFX pipeline."""

from __future__ import annotations

import math
from math import radians

from . import common


def generate(spec: dict) -> dict:
    vfx_spec = spec.get("vfx") or {}
    duration = float(vfx_spec.get("durationSeconds") or 4.0)
    frame_end = max(24, int(duration * 24))
    mats = common.prepare_scene(spec, frame_end=frame_end)
    parts = []
    root = common.create_empty("ANIM_AgentVFX_EffectRoot", "BAKED_EFFECTS", (0, 0, 1.05))
    orbit_root = common.create_empty("ANIM_AgentVFX_OrbitRoot", "BAKED_EFFECTS", (0, 0, 1.05))
    parts.extend([root, orbit_root])
    common.parent_keep_world(orbit_root, root)

    ring = common.cylinder("PROP_AgentVFX_EmissionRing", (0, 0, 1.05), 0.76, 0.04, mats["accent"], vertices=72, rotation=(1.5708, 0, 0), collection_name="BAKED_EFFECTS")
    core = common.uv_sphere("PROP_AgentVFX_SoftCore", (0, -0.01, 1.05), (0.55, 0.04, 0.55), mats["accent"], segments=48, rings=12, collection_name="BAKED_EFFECTS")
    parts.extend([ring, core])
    common.parent_keep_world(ring, root)
    common.parent_keep_world(core, root)

    for index in range(12):
        angle = (math.tau / 12) * index
        radius = 0.75 + (0.08 if index % 2 else 0)
        x = math.cos(angle) * radius
        z = 1.05 + math.sin(angle) * radius
        spark = common.uv_sphere(
            f"PROP_AgentVFX_Spark_{index + 1}",
            (x, -0.03, z),
            (0.035, 0.035, 0.035),
            mats["secondary" if index % 3 else "accent"],
            segments=12,
            rings=6,
            collection_name="BAKED_EFFECTS",
        )
        common.parent_keep_world(spark, orbit_root)
        parts.append(spark)

    for index in range(5):
        y = -0.035 - index * 0.01
        ribbon = common.bevel_curve(
            f"PROP_AgentVFX_Ribbon_{index + 1}",
            [
                (-0.54, y, 0.82 + index * 0.06),
                (-0.12, y, 1.28 - index * 0.04),
                (0.34, y, 0.9 + index * 0.05),
            ],
            mats["accent"],
            bevel_depth=0.016,
            collection_name="BAKED_EFFECTS",
        )
        common.parent_keep_world(ribbon, root)
        parts.append(ribbon)

    ground = common.cylinder("PROP_AgentVFX_GroundGlow", (0, 0, 0.025), 0.86, 0.015, mats["accent"], vertices=72, collection_name="BAKED_EFFECTS")
    ground.scale.y = 0.72
    common.parent_keep_world(ground, root)
    parts.append(ground)

    clip_name = spec.get("animationClips", [{"name": "Loop_Effect"}])[0]["name"]
    common.create_action(
        orbit_root,
        clip_name,
        [
            (1, {"rotation": (0, 0, 0), "scale": (1, 1, 1)}),
            (frame_end // 2, {"rotation": (0, 0, radians(180)), "scale": (1.06, 1.06, 1.06)}),
            (frame_end, {"rotation": (0, 0, radians(360)), "scale": (1, 1, 1)}),
        ],
        end=frame_end,
    )

    common.setup_lighting_and_camera(spec, camera_loc=(2.35, -4.9, 1.75), target=(0, 0, 1.05))
    paths = common.export_asset(spec, parts, animations=True, frame=max(1, frame_end // 3))
    return common.collect_metadata(
        spec,
        paths,
        rig={
            "type": spec.get("rigTarget", "simple transform rig"),
            "root": root.name,
            "animated_controls": [orbit_root.name],
        },
        vfx={
            "family": vfx_spec.get("family", "custom"),
            "emission_source": vfx_spec.get("emissionSource", "free-floating"),
            "transparency_style": vfx_spec.get("transparencyStyle", "mixed"),
            "duration_seconds": duration,
            "loop": bool(vfx_spec.get("loop", True)),
            "texture_dependencies": [],
        },
        notes=[
            "Generated by the reusable OnTheSpectrum VFX pipeline.",
            "VFX is authored as GLB-compatible baked meshes, curves, and transform animation.",
            "No browser-only particle primitive is used as the source of truth.",
            "Mixamo exports are intentionally omitted for VFX assets.",
        ],
    )
